apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-tenant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/X-BRAIN-CDO-09/PhanHoangNhat-aws-accelerator-p2.git
    targetRevision: HEAD
    path: cloud/w10/lab_day4/tenants/payments
  destination:
    server: https://kubernetes.default.svc
    namespace: payments
  syncPolicy:
    automated:
      prune: true
      selfHeal: true